/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.ny.client.ui;

import by.ny.client.ConnectionUtil;
import by.ny.server.entity.User;
import by.ny.server.entity.UserRole;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Natallia Yurush
 */
public class AdministratorWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindow
     */
    public AdministratorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        usersPanel1 = new by.ny.client.ui.UsersPanel();
        creditsPanel1 = new by.ny.client.ui.CreditsPanel();
        requestedCreditsPanel1 = new by.ny.client.ui.RequestedCreditsPanel();
        grantedCreditsPanel1 = new by.ny.client.ui.GrantedCreditsPanel();
        expertMethodPanel1 = new by.ny.client.ui.ExpertMethodPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Кредитная организация (Администратор)");

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });
        tabs.addTab("Пользователи", usersPanel1);
        tabs.addTab("Кредиты", creditsPanel1);
        tabs.addTab("Заявки на кредит", requestedCreditsPanel1);
        tabs.addTab("Предоставленные кредиты", grantedCreditsPanel1);
        tabs.addTab("Оценка целей кредитов", expertMethodPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsStateChanged
                   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.ny.client.ui.CreditsPanel creditsPanel1;
    private by.ny.client.ui.ExpertMethodPanel expertMethodPanel1;
    private by.ny.client.ui.GrantedCreditsPanel grantedCreditsPanel1;
    private by.ny.client.ui.RequestedCreditsPanel requestedCreditsPanel1;
    private javax.swing.JTabbedPane tabs;
    private by.ny.client.ui.UsersPanel usersPanel1;
    // End of variables declaration//GEN-END:variables
}
