/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.ny.client.ui;

import by.ny.client.ConnectionUtil;
import by.ny.server.entity.Credit;
import by.ny.server.entity.command.credit.GetCreditCommand;
import by.ny.server.entity.result.credit.SingleCreditResult;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natallia Yurush
 */
public class CreditObjectivesPanel extends javax.swing.JPanel {
    //private String[] creditsObjectives;
    private ArrayList<String> creditsObjectives;
    
    /**
     * Creates new form CreditObjectivesPanel
     */
    public CreditObjectivesPanel() {
        creditsObjectives = new ArrayList<>();
        initComponents();
        readObjectivesFromFile();
        reloadTable();
        ObjectivesTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    int selectedRow = ObjectivesTable.getSelectedRow();

                    if (selectedRow < 0) {
                        return;
                    }

                    creditObjectiveField.setText(creditsObjectives.get(selectedRow));
                    deleteButton.setEnabled(true);
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ObjectivesTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        creditObjectiveField = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();

        ObjectivesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Номер критерия", "Цель кредита"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ObjectivesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(ObjectivesTable);
        if (ObjectivesTable.getColumnModel().getColumnCount() > 0) {
            ObjectivesTable.getColumnModel().getColumn(1).setResizable(false);
        }

        saveButton.setText("Сохранить");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Удалить");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        creditObjectiveField.setColumns(20);
        creditObjectiveField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        creditObjectiveField.setRows(5);
        jScrollPane2.setViewportView(creditObjectiveField);

        clearButton.setText("Очистить");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(32, 32, 32)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(deleteButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(creditsObjectives.size() == 4) {
            clearCreditFields();
            JOptionPane.showMessageDialog(this, "Невозможно добавить больше 4 целей");
            return;
        }
        
        creditsObjectives.add((String)creditObjectiveField.getText());
        readObjectivesToFile();
        
        clearCreditFields();
        reloadTable();        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearCreditFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String str = creditObjectiveField.getText();
        creditsObjectives.remove(str);
        clearCreditFields();
        reloadTable();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearCreditFields() {
        creditObjectiveField.setText("");
        
        try {
            ObjectivesTable.clearSelection();
        } catch (Exception e) {
            
        }
        deleteButton.setEnabled(false);
    }
    
    private void readObjectivesToFile() {
        try {
            PrintWriter writer = new PrintWriter("output.txt", "windows-1251");
            for(String str : creditsObjectives) {
                writer.write(str + System.getProperty("line.separator"));
                
            }
            writer.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    private void readObjectivesFromFile() {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader( new FileInputStream("output.txt") , "windows-1251"))) {
            String line;
	    while ((line = reader.readLine()) != null) {
                creditsObjectives.add(line);
	    }
        }
            catch (Exception e) {
                e.printStackTrace();
            }
    }
    
    private void reloadTable() {
        int rowsCount = ((DefaultTableModel) ObjectivesTable.getModel()).getRowCount();
            
            for (int i = 0; i < rowsCount; i ++) {
                ((DefaultTableModel) ObjectivesTable.getModel()).removeRow(0);
            }
            
            for (int i = 0; i < creditsObjectives.size(); i ++) {
                Object[] row = new Object[2];
                
                row[0] = i+1;
                row[1] = creditsObjectives.get(i);
                
                ((DefaultTableModel) ObjectivesTable.getModel()).addRow(row);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ObjectivesTable;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea creditObjectiveField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
