/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.ny.client.ui;

/**
 *
 * @author Natallia Yurush
 */
public class ExpertMethodPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpertMethodPanel
     */
    public ExpertMethodPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        creditObjectivesPanel1 = new by.ny.client.ui.CreditObjectivesPanel();
        pairComparisonMethodPanel1 = new by.ny.client.ui.PairComparisonMethodPanel();

        jTabbedPane1.addTab("Критерии", creditObjectivesPanel1);
        jTabbedPane1.addTab("Выставление оценок", pairComparisonMethodPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.ny.client.ui.CreditObjectivesPanel creditObjectivesPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private by.ny.client.ui.PairComparisonMethodPanel pairComparisonMethodPanel1;
    // End of variables declaration//GEN-END:variables
}
