/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.ny.client.ui;

import by.ny.client.ConnectionUtil;
import by.ny.client.CurrentUserUtil;
import by.ny.server.entity.Credit;
import by.ny.server.entity.CreditStatus;
import by.ny.server.entity.UserCredit;
import by.ny.server.entity.command.credit.GetCreditCommand;
import by.ny.server.entity.command.credit.ListCreditsCommand;
import by.ny.server.entity.command.usercredit.DeleteUserCreditCommand;
import by.ny.server.entity.command.usercredit.ListUserCreditCommand;
import by.ny.server.entity.result.credit.CreditsResult;
import by.ny.server.entity.result.credit.SingleCreditResult;
import by.ny.server.entity.result.usercredit.DeleteUserCreditResult;
import by.ny.server.entity.result.usercredit.ListUserCreditResult;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natallia Yurush
 */
public class MyRequestedCreditsPanel extends javax.swing.JPanel {
    private Integer userCreditId;

    
    public MyRequestedCreditsPanel() {
        initComponents();
        reloadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestedCreditsTable = new javax.swing.JTable();
        declineCreditRequestButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(836, 400));

        requestedCreditsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Цель выдачи", "Сумма кредита", "Дата заявки"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestedCreditsTable);

        declineCreditRequestButton.setText("Отозвать заявку");
        declineCreditRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineCreditRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(declineCreditRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(declineCreditRequestButton)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void reloadTableData() {
        try {
            Socket socket = ConnectionUtil.getSocket();
            
            ObjectOutputStream outputStream = new ObjectOutputStream(socket.getOutputStream());
            outputStream.writeObject(new ListUserCreditCommand(CurrentUserUtil.getCurrentUser()));
            
            
            ObjectInputStream inputStream = new ObjectInputStream(socket.getInputStream());
            ListUserCreditResult result = (ListUserCreditResult) inputStream.readObject();
            
            final List<UserCredit> requestedUserCredits = new ArrayList();
            
            for (UserCredit userCredit : result.getUserCredits()) {
                if (userCredit.getStatus() == CreditStatus.REQUESTED) {
                    requestedUserCredits.add(userCredit);
                }
            }
            
            requestedCreditsTable.setModel(new AbstractTableModel() {
                private String columns[] = new String [] { "Цель выдачи", "Сумма кредита", "Дата заявки" };
                
                @Override
                public int getRowCount() {
                    return requestedUserCredits.size();
                }

                @Override
                public int getColumnCount() {
                    return columns.length;
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    UserCredit userCredit = requestedUserCredits.get(rowIndex);
                    
                    if (columnIndex == 0) {
                        try {
                            Socket socket = ConnectionUtil.getSocket();

                            ObjectOutputStream outputStream = new ObjectOutputStream(socket.getOutputStream());
                            outputStream.writeObject(new GetCreditCommand(userCredit.getCreditId()));

                            ObjectInputStream inputStream = new ObjectInputStream(socket.getInputStream());
                            SingleCreditResult result = (SingleCreditResult) inputStream.readObject();
                            Credit credit = result.getCredit();

                            return credit.getPurpose();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else if (columnIndex == 1) {
                        return userCredit.getIssueAmount();
                    } else if (columnIndex == 2) {
                        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

                        return format.format(userCredit.getIssueDate());
                    }
                    return "";
                }
                
                // needed to show column names in JTable
                public String getColumnName(int col) {
                    return columns[col];
                }
                public Class getColumnClass(int col) {
                    if (col == 1) {
                        return Double.class;
                    }
                    else {
                        return String.class;
                    }
                }
            });
            
            requestedCreditsTable.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    int selectedRow = requestedCreditsTable.getSelectedRow();

                    if (selectedRow < 0) {
                        return;
                    }

                    userCreditId = requestedUserCredits.get(selectedRow).getId();
                    declineCreditRequestButton.setEnabled(true);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void declineCreditRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineCreditRequestButtonActionPerformed
        if (userCreditId == null) {
            declineCreditRequestButton.setEnabled(false);
            return;
        }
        
        try {
            Socket socket = ConnectionUtil.getSocket();
            
            ObjectOutputStream outputStream = new ObjectOutputStream(socket.getOutputStream());
            outputStream.writeObject(new DeleteUserCreditCommand(userCreditId));
            
            ObjectInputStream inputStream = new ObjectInputStream(socket.getInputStream());
            DeleteUserCreditResult result = (DeleteUserCreditResult) inputStream.readObject();
            
            if (result.isSuccess()) {
                declineCreditRequestButton.setEnabled(false);
                reloadTableData();
                JOptionPane.showMessageDialog(this, "Заявка успешно отозвана.");
            } else {
                JOptionPane.showMessageDialog(this, "Не удалось отозвать заявку.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_declineCreditRequestButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton declineCreditRequestButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestedCreditsTable;
    // End of variables declaration//GEN-END:variables
}
