/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.ny.client.ui;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Natallia Yurush
 */
public class PairComparisonMethodPanel extends javax.swing.JPanel {
    private ArrayList<String> creditsObjectives;
    private Double[] targetWeights;
    
    public PairComparisonMethodPanel() {
        initComponents();
        targetWeights = new Double[] {0.0, 0.0, 0.0, 0.0};
        creditsObjectives = new ArrayList<>();
        readObjectivesFromFile();
        if(creditsObjectives.size() != 4) {
            JOptionPane.showMessageDialog(this, "В закладке \"Критерии\" должны быть заполнены 4 цели");
            CalculateButton.setEnabled(false);
            RecordAnotherAnswerButton.setEnabled(false);
            SaveButton.setEnabled(false);
            ClearButton.setEnabled(false);
            ScaleSizeField.setEnabled(false);
        } else {
            fillCriteriaField();            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CriteriaField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        field00 = new javax.swing.JTextField();
        field01 = new javax.swing.JTextField();
        field02 = new javax.swing.JTextField();
        field03 = new javax.swing.JTextField();
        field10 = new javax.swing.JTextField();
        field11 = new javax.swing.JTextField();
        field12 = new javax.swing.JTextField();
        field13 = new javax.swing.JTextField();
        field20 = new javax.swing.JTextField();
        field21 = new javax.swing.JTextField();
        field22 = new javax.swing.JTextField();
        field23 = new javax.swing.JTextField();
        field30 = new javax.swing.JTextField();
        field31 = new javax.swing.JTextField();
        field32 = new javax.swing.JTextField();
        field33 = new javax.swing.JTextField();
        RecordAnotherAnswerButton = new javax.swing.JButton();
        CalculateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResponseField = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ScaleSizeField = new javax.swing.JTextField();

        CriteriaField.setColumns(20);
        CriteriaField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CriteriaField.setRows(5);
        jScrollPane1.setViewportView(CriteriaField);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("K1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("K2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("K3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("K4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("K1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("K2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("K3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("K4");

        field00.setEnabled(false);

        field11.setEnabled(false);

        field22.setEnabled(false);

        field33.setEnabled(false);

        RecordAnotherAnswerButton.setText("Записать еще один ответ");
        RecordAnotherAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordAnotherAnswerButtonActionPerformed(evt);
            }
        });

        CalculateButton.setText("Рассчитать ");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Очистить");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ResponseField.setColumns(20);
        ResponseField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ResponseField.setRows(5);
        jScrollPane2.setViewportView(ResponseField);

        SaveButton.setText("Сохранить");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Размер шкалы:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(ScaleSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(RecordAnotherAnswerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(field20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(field10)
                                            .addComponent(field00, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field31, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field01, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(field12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(field02, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31))
                            .addComponent(field32, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(field03)
                                    .addComponent(field13)
                                    .addComponent(field23)
                                    .addComponent(field33, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel4)))
                        .addGap(35, 35, 35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(ScaleSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(field00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(field10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(field20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(field30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecordAnotherAnswerButton)
                    .addComponent(CalculateButton)
                    .addComponent(ClearButton)
                    .addComponent(SaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        clearFields();
        ResponseField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void RecordAnotherAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordAnotherAnswerButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_RecordAnotherAnswerButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if(field01.getText().equals("") || field02.getText().equals("") || field03.getText().equals("") ||
                field10.getText().equals("") || field12.getText().equals("") || field13.getText().equals("") || 
                field20.getText().equals("") || field21.getText().equals("") || field23.getText().equals("") || field30.getText().equals("")
                 || field31.getText().equals("") || field32.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Должны быть заполнены все ячейки матрицы");
            return;
        }
        double temp1 = 0.0, temp2 = 0.0, temp3 = 0.0, temp4 = 0.0;
        
        temp1 = (Double.parseDouble(field01.getText()) + Double.parseDouble(field02.getText()) 
                + Double.parseDouble(field03.getText())) / Integer.parseInt(ScaleSizeField.getText()) / 12;
        
        temp2 = (Double.parseDouble(field10.getText()) + Double.parseDouble(field12.getText()) 
                + Double.parseDouble(field13.getText())) / Integer.parseInt(ScaleSizeField.getText()) / 12;
        
        temp3 = (Double.parseDouble(field20.getText()) + Double.parseDouble(field21.getText()) 
                + Double.parseDouble(field23.getText())) / Integer.parseInt(ScaleSizeField.getText()) / 12;
        
        temp4 = (Double.parseDouble(field30.getText()) + Double.parseDouble(field31.getText()) 
                + Double.parseDouble(field32.getText())) / Integer.parseInt(ScaleSizeField.getText()) / 12;
        
        targetWeights[0] += temp1;
        targetWeights[1] += temp2;
        targetWeights[2] += temp3;
        targetWeights[3] += temp4;
        
        JOptionPane.showMessageDialog(this, "Матрица частот эксперта успешно сформирована");
        
        //clearFields();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        if(targetWeights[0] == 0.0 && targetWeights[1] == 0.0 && targetWeights[2] == 0.0){
            JOptionPane.showMessageDialog(this, "Данные не были введены.");
            return;
        }
        
        String str = "Искомые веса целей:" + System.getProperty("line.separator") + "К1 = " + targetWeights[0].toString()
                + System.getProperty("line.separator") + "К2 = " + targetWeights[1].toString()
                + System.getProperty("line.separator") + "К3 = " + targetWeights[2].toString()
                + System.getProperty("line.separator") + "К4 = " + targetWeights[3].toString()
                + System.getProperty("line.separator") + "Наиболее весомая цель: " + creditsObjectives.get(max());
        
        ResponseField.setText(str);
        clearFields();
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void clearFields(){
        field00.setText("");
        field01.setText("");
        field02.setText("");
        field03.setText("");
        field10.setText("");
        field11.setText("");
        field12.setText("");
        field13.setText("");
        field20.setText("");
        field21.setText("");
        field22.setText("");
        field23.setText("");
        field30.setText("");
        field31.setText("");
        field32.setText("");
        field33.setText("");
        //ResponseField.setText("");
    }
    
    private void readObjectivesFromFile() {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader( new FileInputStream("output.txt") , "windows-1251"))) {
            String line;
	    while ((line = reader.readLine()) != null) {
                creditsObjectives.add(line);
	    }
        }
            catch (Exception e) {
                e.printStackTrace();
            }
    }
    
    private void fillCriteriaField() {
        //System.getProperty("line.separator");
        CriteriaField.setText("Критерии:" + System.getProperty("line.separator") + "К1: " + creditsObjectives.get(0) + System.getProperty("line.separator") 
                + "К2: " + creditsObjectives.get(1) + System.getProperty("line.separator") + "К3: " + creditsObjectives.get(2)
                + System.getProperty("line.separator") + "К4: " + creditsObjectives.get(3));
    }
    
    private Integer max() {
       Integer maxIndex = 0; 
       Double currentNumber;
       for (int i = 1; i < targetWeights.length; i++) {
            currentNumber = targetWeights[i];
            if ((currentNumber > targetWeights[maxIndex])){
                maxIndex = i;
            }
        } 
        return maxIndex; 
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextArea CriteriaField;
    private javax.swing.JButton RecordAnotherAnswerButton;
    private javax.swing.JTextArea ResponseField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField ScaleSizeField;
    private javax.swing.JTextField field00;
    private javax.swing.JTextField field01;
    private javax.swing.JTextField field02;
    private javax.swing.JTextField field03;
    private javax.swing.JTextField field10;
    private javax.swing.JTextField field11;
    private javax.swing.JTextField field12;
    private javax.swing.JTextField field13;
    private javax.swing.JTextField field20;
    private javax.swing.JTextField field21;
    private javax.swing.JTextField field22;
    private javax.swing.JTextField field23;
    private javax.swing.JTextField field30;
    private javax.swing.JTextField field31;
    private javax.swing.JTextField field32;
    private javax.swing.JTextField field33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
